apiVersion: v1
kind: Service
metadata:
  name: myapp-envoy-svc
  namespace: envoy
  labels:
    app: myapp-envoy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 10000
    targetPort: http
    protocol: TCP
  selector:
    app: myapp-envoy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-envoy
  labels:
    app: myapp-envoy
  namespace: envoy
spec:
  selector:
    matchLabels:
      app: myapp-envoy
  template:
    metadata:
      labels:
        app: myapp-envoy
    spec:
      containers:
      - name: myapp-envoy
        image: harbor.local/pmb/envoy:1
        imagePullPolicy: Always
        env:
        - name: "ENVOY_LB_ALG"
          value: "LEAST_REQUEST"
        - name: "SERVICE_NAME"
          value: "myapp"
        ports:
        - name: http
          containerPort: 10000
        - name: envoy-admin
          containerPort: 9901
