apiVersion: v1
kind: Service
metadata:
  name: httpd-discovery
  namespace: envoy
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: nginx-pmb
