apiVersion: v1
kind: Service
metadata:
  name: httpd-discovery
  namespace: envoy
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: nginx-pmb
  type: ClusterIP
