---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: envoy
  labels:
    app: envoy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: envoy


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-configmap
  namespace: envoy
data:
  config: |
    static_resources:

      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      host_rewrite_literal: www.envoyproxy.io
                      cluster: service_envoyproxy_io

      clusters:
      - name: service_envoyproxy_io
        type: LOGICAL_DNS
        # Comment out the following line to test on v6 networks
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: service_envoyproxy_io
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: www.envoyproxy.io
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: www.envoyproxy.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: envoy
      app: envoy
  template:
    metadata:
      labels:
        service: envoy
        app: envoy
    spec:
      volumes:
      - name: config
        configMap:
          name: envoy-configmap
          items:
          - key: config
            path: envoy.yaml
      containers:
        - name: envoy
          #image: envoyproxy/envoy-alpine:v1.13.1
          image: envoyproxy/envoy-dev:8537d2a29265e61aaa0349311e6fc5d592659b08
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
              readOnly: true
